---
- name: install haproxy

  hosts: loadbalancer
  become: true


  tasks:
   - name: install haproxy
     apt:
       name: haproxy
       state: present

   - name: Generate ha-proxy configuration file
     template:
       src: haproxy.cfg
       dest: "/etc/haproxy/haproxy.cfg"
#       owner: root
#       group: root
#       mode: 0600
#     tags:
#       - haproxy
#      - restart haproxy
   - name: "start service of haproxy"
     service:
       name: "haproxy"
       state: restarted
