
---
- name: Webserver installation
  hosts: webserver001
  become: true



  tasks:
    - name: Install UFW
      apt:
       name: ufw
       state: present
    - name: Setup rules
      command: "{{ item }}"
      with_items:
        - ufw default deny incoming
        - ufw allow ssh
        - ufw allow http
        - ufw allow https
        - ufw --force enable

    - name: nginx
      apt: 
       name: nginx
       state: present

    - name: Delete content & directory
      file:
       state: absent
       path: "/var/www/html/index.nginx-debian.html"

    - name: "copying the web pages"
      template:
       src: "index.html"
       dest: "/var/www/html/index.html"

    - name: "start nginx"
      service:
       name: "nginx"
       state: started
